### ISSUE TITLE
last version is not up to date (npm)

### ISSUE THREAD

**Issue by Dioude** [hggeorgiev/ngx-image-editor#11]
Hi,
I've noticed that the last version 1.3.0 doesn't have all the commits from master, and it's preventing me from building my project using "--prod" I got this error "ERROR in node_modules/ngx-image-editor/ngx-image-editor.d.ts.NgxImageEditorComponent.html(5,40): : Property 'name' does not exist on type 'EditorOptions'." which seems to have been fixed in master.

Is it possible to have an updated version for npm ? 
Thanks

**Comment by hggeorgiev** [comment]
Hello @Dioude. v1.4.1 has just been released. There's also a new [demo on Slackblitz](https://stackblitz.com/edit/ngx-image-editor-demo) you can check out.
