### ISSUE TITLE
Firebase storage image url has been blocked by CORS policy: No 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by iamnaj1** [hggeorgiev/ngx-image-editor#19]
I want to edit my image from my firebase storage. I put the firebase image url in ImageUrl config of ngxImageEditor but I'm having this CORS error. The editor is working fine but the image is not loaded.

**Comment by hggeorgiev** [comment]
Closing this because it's not related to the image editor and its functionalities.
